package com.example.db.entity;

public class Right {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.PID
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.PERMISSION
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.IMAGE
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.INDEX_NO
     *
     * @mbggenerated
     */
    private Integer indexNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.IS_SHOW
     *
     * @mbggenerated
     */
    private String isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.ID
     *
     * @return the value of SYS_RIGHT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.ID
     *
     * @param id the value for SYS_RIGHT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.PID
     *
     * @return the value of SYS_RIGHT.PID
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.PID
     *
     * @param pid the value for SYS_RIGHT.PID
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.NAME
     *
     * @return the value of SYS_RIGHT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.NAME
     *
     * @param name the value for SYS_RIGHT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.TYPE
     *
     * @return the value of SYS_RIGHT.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.TYPE
     *
     * @param type the value for SYS_RIGHT.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.PERMISSION
     *
     * @return the value of SYS_RIGHT.PERMISSION
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.PERMISSION
     *
     * @param permission the value for SYS_RIGHT.PERMISSION
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.URL
     *
     * @return the value of SYS_RIGHT.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.URL
     *
     * @param url the value for SYS_RIGHT.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.IMAGE
     *
     * @return the value of SYS_RIGHT.IMAGE
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.IMAGE
     *
     * @param image the value for SYS_RIGHT.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.INDEX_NO
     *
     * @return the value of SYS_RIGHT.INDEX_NO
     *
     * @mbggenerated
     */
    public Integer getIndexNo() {
        return indexNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.INDEX_NO
     *
     * @param indexNo the value for SYS_RIGHT.INDEX_NO
     *
     * @mbggenerated
     */
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.IS_SHOW
     *
     * @return the value of SYS_RIGHT.IS_SHOW
     *
     * @mbggenerated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.IS_SHOW
     *
     * @param isShow the value for SYS_RIGHT.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }
}