package com.example.db.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_DESC
     *
     * @mbggenerated
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_LEVEL
     *
     * @mbggenerated
     */
    private String roleLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.STOP_SIGN
     *
     * @mbggenerated
     */
    private String stopSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ID
     *
     * @return the value of SYS_ROLE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ID
     *
     * @param id the value for SYS_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_CODE
     *
     * @return the value of SYS_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_CODE
     *
     * @param roleCode the value for SYS_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @return the value of SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_DESC
     *
     * @return the value of SYS_ROLE.ROLE_DESC
     *
     * @mbggenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_DESC
     *
     * @param roleDesc the value for SYS_ROLE.ROLE_DESC
     *
     * @mbggenerated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_LEVEL
     *
     * @return the value of SYS_ROLE.ROLE_LEVEL
     *
     * @mbggenerated
     */
    public String getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_LEVEL
     *
     * @param roleLevel the value for SYS_ROLE.ROLE_LEVEL
     *
     * @mbggenerated
     */
    public void setRoleLevel(String roleLevel) {
        this.roleLevel = roleLevel == null ? null : roleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.STOP_SIGN
     *
     * @return the value of SYS_ROLE.STOP_SIGN
     *
     * @mbggenerated
     */
    public String getStopSign() {
        return stopSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.STOP_SIGN
     *
     * @param stopSign the value for SYS_ROLE.STOP_SIGN
     *
     * @mbggenerated
     */
    public void setStopSign(String stopSign) {
        this.stopSign = stopSign == null ? null : stopSign.trim();
    }
}