package com.example.db.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_KEY
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PERSON_NAME
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.IDCARD
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.BIRTHDATE
     *
     * @mbggenerated
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REGISTER_DATE
     *
     * @mbggenerated
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.STOP_SIGN
     *
     * @mbggenerated
     */
    private String stopSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.DEL_SIGN
     *
     * @mbggenerated
     */
    private String delSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.IMAGE
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID
     *
     * @return the value of SYS_USER.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID
     *
     * @param id the value for SYS_USER.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_KEY
     *
     * @return the value of SYS_USER.USER_KEY
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_KEY
     *
     * @param userKey the value for SYS_USER.USER_KEY
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey == null ? null : userKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_NAME
     *
     * @return the value of SYS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_NAME
     *
     * @param userName the value for SYS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PASSWORD
     *
     * @return the value of SYS_USER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PASSWORD
     *
     * @param password the value for SYS_USER.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PERSON_NAME
     *
     * @return the value of SYS_USER.PERSON_NAME
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PERSON_NAME
     *
     * @param personName the value for SYS_USER.PERSON_NAME
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.IDCARD
     *
     * @return the value of SYS_USER.IDCARD
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.IDCARD
     *
     * @param idcard the value for SYS_USER.IDCARD
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.SEX
     *
     * @return the value of SYS_USER.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.SEX
     *
     * @param sex the value for SYS_USER.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.BIRTHDATE
     *
     * @return the value of SYS_USER.BIRTHDATE
     *
     * @mbggenerated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.BIRTHDATE
     *
     * @param birthdate the value for SYS_USER.BIRTHDATE
     *
     * @mbggenerated
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PHONE
     *
     * @return the value of SYS_USER.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PHONE
     *
     * @param phone the value for SYS_USER.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.EMAIL
     *
     * @return the value of SYS_USER.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.EMAIL
     *
     * @param email the value for SYS_USER.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REGISTER_DATE
     *
     * @return the value of SYS_USER.REGISTER_DATE
     *
     * @mbggenerated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REGISTER_DATE
     *
     * @param registerDate the value for SYS_USER.REGISTER_DATE
     *
     * @mbggenerated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.STOP_SIGN
     *
     * @return the value of SYS_USER.STOP_SIGN
     *
     * @mbggenerated
     */
    public String getStopSign() {
        return stopSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.STOP_SIGN
     *
     * @param stopSign the value for SYS_USER.STOP_SIGN
     *
     * @mbggenerated
     */
    public void setStopSign(String stopSign) {
        this.stopSign = stopSign == null ? null : stopSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.DEL_SIGN
     *
     * @return the value of SYS_USER.DEL_SIGN
     *
     * @mbggenerated
     */
    public String getDelSign() {
        return delSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.DEL_SIGN
     *
     * @param delSign the value for SYS_USER.DEL_SIGN
     *
     * @mbggenerated
     */
    public void setDelSign(String delSign) {
        this.delSign = delSign == null ? null : delSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.IMAGE
     *
     * @return the value of SYS_USER.IMAGE
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.IMAGE
     *
     * @param image the value for SYS_USER.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}