server:
    port: 8001
    session:
      timeout: 6000 #second

spring:
    aop:
      auto: true
      proxy-target-class: true
    main:
      banner-mode: "console"         #banner打印的位置，可选参数（console, log, off）

#      配置datasource
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: springbootdemo
      password: fengtangzheng
      driver-class-name: oracle.jdbc.driver.OracleDriver

#    mvc:
#      view:
#        suffix: .vm
#        prefix: classpath:/templates/

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      excluded-view-names:
      encoding: UTF-8
      enabled: true
      content-type: text/html
      check-template-location: true

    velocity:
      cache: false
      charset: UTF-8
      expose-spring-macro-helpers: true
      properties:
        velocimacro.library: macro/macro.vm
        velocimacro.library.autoreload: true
      resource-loader-path: classpath:/templates/
      suffix: .vm

    devtools:
      restart:
        exclude: templates
        enabled: true
        trigger-file: classpath:/restart-trigger.xml
      livereload:
        enabled: false

#        自定义banner
banner:
  charset: UTF-8
  location: classpath:/banner.txt


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.db.entity
