package com.example.db.mapper;

import com.example.db.entity.Right;

import java.util.List;

public interface RightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    int insertSelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    Right selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Right record);

    List<Right> selectRightsByRoleId(String roleId);

    List<Right> selectRightByUserId(String userId);
}